// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Zo-GcZPcJ_zhYOkDarPg395MQVgwdu0',
    appId: '1:453391748408:web:80bee3e776619b873f45cd',
    messagingSenderId: '453391748408',
    projectId: 'truckjobsappau',
    authDomain: 'truckjobsappau.firebaseapp.com',
    storageBucket: 'truckjobsappau.firebasestorage.app',
    measurementId: 'G-EF7CHW24R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD73JzZ9d_9_VwI7HbeKCsdRvdCkSjIgN4',
    appId: '1:453391748408:android:bdbdd7b1cee41a943f45cd',
    messagingSenderId: '453391748408',
    projectId: 'truckjobsappau',
    storageBucket: 'truckjobsappau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHWA--2pcT9OSU5ghkAnP6yPjsCcjlhA',
    appId: '1:453391748408:ios:135b6ec06dea86193f45cd',
    messagingSenderId: '453391748408',
    projectId: 'truckjobsappau',
    storageBucket: 'truckjobsappau.firebasestorage.app',
    iosBundleId: 'com.example.truckjobsAu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Zo-GcZPcJ_zhYOkDarPg395MQVgwdu0',
    appId: '1:453391748408:web:b1838ac54d7c61a63f45cd',
    messagingSenderId: '453391748408',
    projectId: 'truckjobsappau',
    authDomain: 'truckjobsappau.firebaseapp.com',
    storageBucket: 'truckjobsappau.firebasestorage.app',
    measurementId: 'G-YF3G2PXTL1',
  );
}
